# Generated by Django 5.2.4 on 2025-08-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('avg_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('sector', models.CharField(max_length=50)),
                ('market_cap', models.CharField(max_length=10)),
            ],
        ),
    ]
